"""added relationsip in tables

Revision ID: a6c474d53723
Revises: 14b83d5013ea
Create Date: 2026-05-21 10:20:27.927500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c474d53723'
down_revision: Union[str, Sequence[str], None] = '14b83d5013ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_user_tasks", 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_tasks", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
